name: console_full_project
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  calculator:
    path: 'packages/calculator'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
